### PR TITLE
Withdraw and Deposit Exact One token to pool with Latest Layout

### PR DESCRIPTION
**Pull request by yamijuan**
DEPOSIT
radio

WITHDRAW
radioremove

### CODE REVIEW

**Comment by yamijuan** [comment]
added a short text as popover 
image

**Comment by SensyCheung** [comment]
It seems difficult to understand this feature.

**Comment by ghost** [comment]
Does this work? I tried a number of things after merging, and nothing is showing up. How to enable?

**Comment by bartosz-lipinski** [comment]
Yes, it does, but it requires a new smart contract which should be deployed soon (waiting for upgradable loaders). Next time we will add a feature flag.

**Pull request merged**
