### PR TITLE
Add support for Solong wallet extension

### PR DESCRIPTION
**Pull request by cz-theng**
The [SolongWallet Chrome Extension](http://solongwallet.com/) has already publish on [Chome extension store](https://chrome.google.com/webstore/category/extensions).

And we add SolongAdapter which works like [sol-wallet-adapter](https://github.com/project-serum/sol-wallet-adapter)
to support Dapps which already use [sol-wallet-adapter](https://github.com/project-serum/sol-wallet-adapter)

### CODE REVIEW

**Comment by bartosz-lipinski** [comment]
Looks awesome thanks for adding it

**Comment by bartosz-lipinski** [comment]
@cz-it when are you planning to stop displaying separate window and use extension instead?

**Comment by cz-theng** [comment]
> @cz-it when are you planning to stop displaying separate window and use extension instead?

Here:

https://github.com/project-serum/oyster-swap/blob/233c4fa6665469db1ac95b504a3402f72a8f7f9d/src/utils/wallet.tsx#L24



when select ”solongwallet.com“ provider，it will use SolongAdapter to use extension.

**Comment by bartosz-lipinski** [comment]
@cz-it I was asking more about workflow with chrome extension. Right now when you connect you display new window instead of using popup like metamask. Anyway to position that window right under extension icon?

**Comment by cz-theng** [comment]
Infact metamask's popup is also a chrome extension window for a Dapp. 
Only click the icon right on the location bar will popup the a window under extension ico.
Solong does the same thing,and new window is on right top of browser.

**Comment by cz-theng** [comment]
> @cz-it I was asking more about workflow with chrome extension. Right now when you connect you display new window instead of using popup like metamask. Anyway to position that window right under extension icon?

Infact metamask's popup is also a chrome extension window for a Dapp.
Only click the icon right on the location bar will popup the a window under extension ico.
Solong does the same thing,and new window is on right top of browser.

**Comment by cz-theng** [comment]
> @cz-it I was asking more about workflow with chrome extension. Right now when you connect you display new window instead of using popup like metamask. Anyway to position that window right under extension icon?

10981605337581_ pic
10991605337583_ pic

metamask VS solong . Take care of header of the window. All are the same one .

**Pull request merged**
